# .github/workflows/main.yml

name: CI-ML-Pipeline

# Déclencheur : à chaque push sur main ou exécution manuelle
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Récupérer le code
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Étape 2: Configurer Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Étape 3: Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader stopwords punkt punkt_tab wordnet

      # Étape 4: Exécuter tout le pipeline de données et ML
      - name: Run Data and ML Pipeline
        run: |
          python src/load_data.py
          python src/preprocess.py
          python src/train.py
          python src/evaluate.py

      # Étape 5: Sauvegarder les résultats MLflow (artefacts)
      - name: Upload MLflow results
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results
          path: mlruns/
